### ISSUE TITLE
Make development.ini compatible with Jinja2 > 3

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis_demo_cookiecutter#13]
The current development.ini loads an extensions jinja2.ext.with_ that was removed in Jinja2 version 3. This leads to errors such as OnroerendErfgoed/atramhasis#747 Easiest fix seems to be to remove the with_ extension from the development.ini

**Comment by koenedaele** [comment]
The with extension no longer exists in jinja2 3.x, but we've also removed all with statements from Atramhasis 2.0.0. So, once we release 2.0 it's safe to remove the with extension from the ini file.

**Comment by goessebr** [comment]
The cookiecutter code was integrated in atramhasis since release 2.1.0: https://github.com/OnroerendErfgoed/atramhasis/releases/tag/2.1.0

Documentation can be found at:
- Create your own custom project: https://atramhasis.readthedocs.io/en/latest/customisation.html#creating-your-own-project
- Create a demo project: https://atramhasis.readthedocs.io/en/latest/demo.html#running-a-demo-site-with-cookiecutter
